-- Script SQL sécurisé pour créer toutes les tables nécessaires pour DriveSmart
-- Base de données Oracle
-- Ce script vérifie l'existence des tables avant de les créer

-- Table CONDIDAT (Candidats)
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE CONDIDAT (
        cin_condidat NUMBER(8) PRIMARY KEY,
        nom VARCHAR2(100) NOT NULL,
        prenom VARCHAR2(100) NOT NULL,
        sexe VARCHAR2(1) NOT NULL CHECK (sexe IN (''H'', ''F'')),
        date_naissance DATE NOT NULL,
        tel NUMBER(8) NOT NULL,
        type_permis VARCHAR2(50) NOT NULL
    )';
    DBMS_OUTPUT.PUT_LINE('Table CONDIDAT créée avec succès');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Table CONDIDAT existe déjà');
        ELSE
            RAISE;
        END IF;
END;
/

-- Table VEHICULE
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE VEHICULE (
        MATRICULE VARCHAR2(20) PRIMARY KEY,
        MODELE VARCHAR2(100) NOT NULL,
        KILOMETRAGE NUMBER(10) NOT NULL,
        DISPONIBILITE VARCHAR2(20) NOT NULL CHECK (DISPONIBILITE IN (''Libre'', ''Réservé'', ''En service'')),
        TYPE_ENERGIE VARCHAR2(50) NOT NULL,
        ETAT_MAINTENANCE VARCHAR2(50) NOT NULL,
        DATE_MAINTENANCE DATE NOT NULL
    )';
    DBMS_OUTPUT.PUT_LINE('Table VEHICULE créée avec succès');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Table VEHICULE existe déjà');
        ELSE
            RAISE;
        END IF;
END;
/

-- Table EXAMEN
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE EXAMEN (
        ID_EXAMEN VARCHAR2(50) PRIMARY KEY,
        TYPE_EXAMEN VARCHAR2(50) NOT NULL CHECK (TYPE_EXAMEN IN (''code'', ''conduit'')),
        TYPE_PERMIS VARCHAR2(50) NOT NULL,
        DATE_EXAMEN DATE NOT NULL
    )';
    DBMS_OUTPUT.PUT_LINE('Table EXAMEN créée avec succès');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Table EXAMEN existe déjà');
        ELSE
            RAISE;
        END IF;
END;
/

-- Table EMPLOYEE (Moniteurs/Employés)
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE EMPLOYEE (
        ID_EMPLOYEE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        NOM VARCHAR2(100) NOT NULL,
        PRENOM VARCHAR2(100) NOT NULL,
        CIN NUMBER(8) UNIQUE,
        TEL NUMBER(8),
        EMAIL VARCHAR2(100),
        DATE_EMBAUCHE DATE,
        POSTE VARCHAR2(50)
    )';
    DBMS_OUTPUT.PUT_LINE('Table EMPLOYEE créée avec succès');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Table EMPLOYEE existe déjà');
        ELSE
            RAISE;
        END IF;
END;
/

-- Table PLANNING (Séances de conduite) - LA PLUS IMPORTANTE
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE PLANNING (
        "ID_SÉANCE" NUMBER PRIMARY KEY,
        "DATE_SEANCE" DATE NOT NULL,
        "NOM_CANDIDAT" VARCHAR2(200),
        "TYPE_SÉANCE" VARCHAR2(50) NOT NULL CHECK ("TYPE_SÉANCE" IN (''code'', ''conduit'')),
        "HEURE_DEBUT" TIMESTAMP NOT NULL,
        "HEURE_FIN" VARCHAR2(10) NOT NULL,
        "ADRESSE_CIRCUIT" VARCHAR2(200) NOT NULL,
        "NOM_MONITEUR" VARCHAR2(200),
        "VEHICULE" VARCHAR2(20),
        CONSTRAINT FK_PLANNING_VEHICULE FOREIGN KEY ("VEHICULE") REFERENCES VEHICULE(MATRICULE)
    )';
    DBMS_OUTPUT.PUT_LINE('Table PLANNING créée avec succès');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Table PLANNING existe déjà');
        ELSE
            RAISE;
        END IF;
END;
/

-- Séquence pour générer les IDs de séance
BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_PLANNING
        START WITH 1
        INCREMENT BY 1
        NOCACHE
        NOCYCLE';
    DBMS_OUTPUT.PUT_LINE('Séquence SEQ_PLANNING créée avec succès');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Séquence SEQ_PLANNING existe déjà');
        ELSE
            RAISE;
        END IF;
END;
/

-- Alternative séquence (au cas où)
BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_PLANNING_ID
        START WITH 1
        INCREMENT BY 1
        NOCACHE
        NOCYCLE';
    DBMS_OUTPUT.PUT_LINE('Séquence SEQ_PLANNING_ID créée avec succès');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Séquence SEQ_PLANNING_ID existe déjà');
        ELSE
            RAISE;
        END IF;
END;
/

-- Index pour améliorer les performances
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_PLANNING_DATE ON PLANNING("DATE_SEANCE")';
    DBMS_OUTPUT.PUT_LINE('Index IDX_PLANNING_DATE créé');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Index IDX_PLANNING_DATE existe déjà');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_PLANNING_CANDIDAT ON PLANNING("NOM_CANDIDAT")';
    DBMS_OUTPUT.PUT_LINE('Index IDX_PLANNING_CANDIDAT créé');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Index IDX_PLANNING_CANDIDAT existe déjà');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_PLANNING_MONITEUR ON PLANNING("NOM_MONITEUR")';
    DBMS_OUTPUT.PUT_LINE('Index IDX_PLANNING_MONITEUR créé');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Index IDX_PLANNING_MONITEUR existe déjà');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_CONDIDAT_CIN ON CONDIDAT(cin_condidat)';
    DBMS_OUTPUT.PUT_LINE('Index IDX_CONDIDAT_CIN créé');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Index IDX_CONDIDAT_CIN existe déjà');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_VEHICULE_MATRICULE ON VEHICULE(MATRICULE)';
    DBMS_OUTPUT.PUT_LINE('Index IDX_VEHICULE_MATRICULE créé');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('Index IDX_VEHICULE_MATRICULE existe déjà');
        ELSE
            RAISE;
        END IF;
END;
/

-- Commentaires sur les tables
BEGIN
    EXECUTE IMMEDIATE 'COMMENT ON TABLE CONDIDAT IS ''Table des candidats pour le permis de conduire''';
    EXECUTE IMMEDIATE 'COMMENT ON TABLE VEHICULE IS ''Table des véhicules de l''''auto-école''';
    EXECUTE IMMEDIATE 'COMMENT ON TABLE EXAMEN IS ''Table des examens de code et de conduite''';
    EXECUTE IMMEDIATE 'COMMENT ON TABLE EMPLOYEE IS ''Table des employés/moniteurs de l''''auto-école''';
    EXECUTE IMMEDIATE 'COMMENT ON TABLE PLANNING IS ''Table de planification des séances de conduite''';
    DBMS_OUTPUT.PUT_LINE('Commentaires ajoutés aux tables');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erreur lors de l''ajout des commentaires: ' || SQLERRM);
END;
/

COMMIT;

DBMS_OUTPUT.PUT_LINE('========================================');
DBMS_OUTPUT.PUT_LINE('Script terminé avec succès!');
DBMS_OUTPUT.PUT_LINE('Toutes les tables ont été créées ou existaient déjà.');
DBMS_OUTPUT.PUT_LINE('========================================');

