#include "gestion_equipement.h"
#include "ui_gestion_equipement.h"
#include "connection.h"
#include <QMainWindow>
#include <QMessageBox>
#include <QStackedWidget>
#include <QSqlQuery>
#include <QSqlError>
#include <QSqlQueryModel>
#include <QDebug>
#include <QFileDialog>
#include <QTextStream>
#include <QDate>
#include <QNetworkAccessManager>
#include <QNetworkRequest>
#include <QNetworkReply>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>

Gestion_Equipement::Gestion_Equipement(QWidget *parent) :
    QWidget(parent),
    ui(new Ui::Gestion_Equipement)
{
    ui->setupUi(this);

    // Initialize model
    model = new QSqlQueryModel(this);
    
    // Setup combobox for categories
    ui->comboBox_equipement->addItem("Sécurité");
    ui->comboBox_equipement->addItem("Véhicule");
    ui->comboBox_equipement->addItem("Signalisation");
    ui->comboBox_equipement->addItem("Bureautique");
    ui->comboBox_equipement->addItem("Autre");
    
    // Setup combobox for état
    ui->comboBox->addItem("Disponible");
    ui->comboBox->addItem("En maintenance");
    ui->comboBox->addItem("Hors service");
    
    // Make ID field read-only (auto-generated by database)
    ui->id_equipement->setReadOnly(true);
    ui->id_equipement->setStyleSheet("background-color: #f0f0f0; border: 2px solid #cccccc;");
    
    // Load initial data
    loadTableData();
    
    // Connect navigation buttons
    connect(ui->candidat, &QPushButton::clicked, this, &Gestion_Equipement::navigateToCandidat);
    connect(ui->planning, &QPushButton::clicked, this, &Gestion_Equipement::navigateToPlanning);
    connect(ui->employee, &QPushButton::clicked, this, &Gestion_Equipement::navigateToEmployee);
    connect(ui->vehicule, &QPushButton::clicked, this, &Gestion_Equipement::navigateToVehicule);
    connect(ui->examen, &QPushButton::clicked, this, &Gestion_Equipement::navigateToExamen);
    connect(ui->equipement, &QPushButton::clicked, this, &Gestion_Equipement::navigateToEquipement);
    
    // Connect search and filter
    connect(ui->recherche_2, &QTextEdit::textChanged, this, &Gestion_Equipement::on_recherche_2_textChanged);
    connect(ui->tri_2, QOverload<int>::of(&QComboBox::currentIndexChanged), this, &Gestion_Equipement::on_tri_2_currentIndexChanged);
    
    // Connect table selection
    connect(ui->tab_2, &QTableWidget::clicked, this, &Gestion_Equipement::on_tab_2_clicked);
}

Gestion_Equipement::~Gestion_Equipement()
{
    delete ui;
    delete model;
}

// ==================== CRUD OPERATIONS ====================

// CREATE - Add new equipment
void Gestion_Equipement::on_btn_ajout_clicked()
{
    if (!validateInput()) {
        return;
    }
    
    // Generate next ID
    int newId = generateNextId();
    
    QSqlQuery query;
    query.prepare("INSERT INTO EQUIPEMENT (ID_EQUIPEMENT, NOM, CATEGORIE, QUANTITE_TOTALE, QUANTITE_DISPONIBLE, ETAT, FOURNISSEUR, DATE_ACQUISITION) "
                  "VALUES (:id, :nom, :categorie, :qteTotale, :qteDispo, :etat, :fournisseur, TO_DATE(:dateAcq, 'YYYY-MM-DD'))");
    
    query.bindValue(":id", newId);
    query.bindValue(":nom", ui->nom_equipement->toPlainText().trimmed());
    query.bindValue(":categorie", ui->comboBox_equipement->currentText());
    query.bindValue(":qteTotale", ui->spinBox_equipement->value());
    query.bindValue(":qteDispo", ui->spinBox_equipement1->value());
    query.bindValue(":etat", ui->comboBox->currentText());
    query.bindValue(":fournisseur", ui->nom_equipement_2->toPlainText().trimmed());
    query.bindValue(":dateAcq", ui->dateEdit->date().toString("yyyy-MM-dd"));
    
    if (query.exec()) {
        QMessageBox::information(this, "Succès", "Équipement ajouté avec succès!");
        loadTableData();
        clearForm();
    } else {
        QMessageBox::critical(this, "Erreur", "Erreur lors de l'ajout: " + query.lastError().text());
    }
}

// READ - Load data into table
void Gestion_Equipement::loadTableData()
{
    QSqlQuery query("SELECT ID_EQUIPEMENT, NOM, CATEGORIE, QUANTITE_TOTALE, QUANTITE_DISPONIBLE, ETAT, FOURNISSEUR, DATE_ACQUISITION FROM EQUIPEMENT");
    
    ui->tab_2->setRowCount(0);
    ui->tab_2->setColumnCount(8);
    
    QStringList headers;
    headers << "ID" << "Nom" << "Catégorie" << "Qté Totale" << "Qté Dispo" << "État" << "Fournisseur" << "Date Acquisition";
    ui->tab_2->setHorizontalHeaderLabels(headers);
    
    int row = 0;
    while (query.next()) {
        ui->tab_2->insertRow(row);
        
        for (int col = 0; col < 8; col++) {
            QTableWidgetItem *item = new QTableWidgetItem(query.value(col).toString());
            if (col == 0) { // ID column - read only
                item->setFlags(item->flags() & ~Qt::ItemIsEditable);
            }
            ui->tab_2->setItem(row, col, item);
        }
        row++;
    }
    
    // Adjust column widths
    ui->tab_2->resizeColumnsToContents();
}

// UPDATE - Modify existing equipment
void Gestion_Equipement::on_pushButton_4_clicked()
{
    QString id = ui->id_equipement->toPlainText().trimmed();
    
    if (id.isEmpty()) {
        QMessageBox::warning(this, "Attention", "Veuillez sélectionner un équipement à modifier.");
        return;
    }
    
    if (!validateInput()) {
        return;
    }
    
    QSqlQuery query;
    query.prepare("UPDATE EQUIPEMENT SET NOM=:nom, CATEGORIE=:categorie, QUANTITE_TOTALE=:qteTotale, "
                  "QUANTITE_DISPONIBLE=:qteDispo, ETAT=:etat, FOURNISSEUR=:fournisseur, DATE_ACQUISITION=TO_DATE(:dateAcq, 'YYYY-MM-DD') "
                  "WHERE ID_EQUIPEMENT=:id");
    
    query.bindValue(":id", id.toInt());
    query.bindValue(":nom", ui->nom_equipement->toPlainText().trimmed());
    query.bindValue(":categorie", ui->comboBox_equipement->currentText());
    query.bindValue(":qteTotale", ui->spinBox_equipement->value());
    query.bindValue(":qteDispo", ui->spinBox_equipement1->value());
    query.bindValue(":etat", ui->comboBox->currentText());
    query.bindValue(":fournisseur", ui->nom_equipement_2->toPlainText().trimmed());
    query.bindValue(":dateAcq", ui->dateEdit->date().toString("yyyy-MM-dd"));
    
    if (query.exec()) {
        QMessageBox::information(this, "Succès", "Équipement modifié avec succès!");
        loadTableData();
        clearForm();
    } else {
        QMessageBox::critical(this, "Erreur", "Erreur lors de la modification: " + query.lastError().text());
    }
}

// DELETE - Remove equipment
void Gestion_Equipement::on_pushButton_3_clicked()
{
    QString id = ui->id_equipement->toPlainText().trimmed();
    
    if (id.isEmpty()) {
        QMessageBox::warning(this, "Attention", "Veuillez sélectionner un équipement à supprimer.");
        return;
    }
    
    QMessageBox::StandardButton reply;
    reply = QMessageBox::question(this, "Confirmation", 
                                  "Êtes-vous sûr de vouloir supprimer cet équipement?",
                                  QMessageBox::Yes | QMessageBox::No);
    
    if (reply == QMessageBox::Yes) {
        QSqlQuery query;
        query.prepare("DELETE FROM EQUIPEMENT WHERE ID_EQUIPEMENT=:id");
        query.bindValue(":id", id.toInt());
        
        if (query.exec()) {
            QMessageBox::information(this, "Succès", "Équipement supprimé avec succès!");
            loadTableData();
            clearForm();
        } else {
            QMessageBox::critical(this, "Erreur", "Erreur lors de la suppression: " + query.lastError().text());
        }
    }
}

// Clear form fields
void Gestion_Equipement::on_btn_reset_clicked()
{
    clearForm();
}

// ==================== ADDITIONAL FEATURES ====================

void Gestion_Equipement::on_btnUpdateMaintenance_clicked()
{
    // Check maintenance status based on equipment condition
    QSqlQuery query("SELECT COUNT(*) FROM EQUIPEMENT WHERE ETAT = 'En maintenance' OR ETAT = 'Hors service'");
    
    int maintenanceCount = 0;
    QSqlQuery totalQuery("SELECT COUNT(*) FROM EQUIPEMENT");
    int totalCount = 0;
    
    if (query.next()) {
        maintenanceCount = query.value(0).toInt();
    }
    
    if (totalQuery.next()) {
        totalCount = totalQuery.value(0).toInt();
    }
    
    if (totalCount > 0) {
        int percentage = ((totalCount - maintenanceCount) * 100) / totalCount;
        ui->progressBar->setValue(percentage);
        
        if (percentage >= 80) {
            ui->label_12->setText("Statut : ✓ À jour");
            ui->label_12->setStyleSheet("color: green; font-weight: bold;");
        } else if (percentage >= 50) {
            ui->label_12->setText("Statut : ⚠ Attention requise");
            ui->label_12->setStyleSheet("color: orange; font-weight: bold;");
        } else {
            ui->label_12->setText("Statut : ✗ Maintenance urgente");
            ui->label_12->setStyleSheet("color: red; font-weight: bold;");
        }
        
        QMessageBox::information(this, "Maintenance", 
                                QString("Statut mis à jour!\n%1 équipements sur %2 sont opérationnels.")
                                .arg(totalCount - maintenanceCount)
                                .arg(totalCount));
    }
}

void Gestion_Equipement::on_btnCheckWeather_clicked()
{
    QString ville = ui->lineEditVille->toPlainText().trimmed();
    
    if (ville.isEmpty()) {
        QMessageBox::warning(this, "Attention", "Veuillez entrer un nom de ville.");
        return;
    }
    
    // Note: For a real implementation, you would need an API key from a weather service
    // This is a simplified example showing the structure
    
    QNetworkAccessManager *manager = new QNetworkAccessManager(this);
    
    // Example using OpenWeatherMap API (you need to replace YOUR_API_KEY)
    QString apiKey = "YOUR_API_KEY"; // Get a free key from openweathermap.org
    QString url = QString("http://api.openweathermap.org/data/2.5/weather?q=%1&appid=%2&units=metric&lang=fr")
                      .arg(ville)
                      .arg(apiKey);
    
    QNetworkRequest request(url);
    QNetworkReply *reply = manager->get(request);
    
    connect(reply, &QNetworkReply::finished, [this, reply]() {
        if (reply->error() == QNetworkReply::NoError) {
            QByteArray response = reply->readAll();
            QJsonDocument jsonDoc = QJsonDocument::fromJson(response);
            QJsonObject jsonObj = jsonDoc.object();
            
            if (jsonObj.contains("main")) {
                QJsonObject main = jsonObj["main"].toObject();
                double temp = main["temp"].toDouble();
                
                QJsonArray weatherArray = jsonObj["weather"].toArray();
                QString description = "N/A";
                if (!weatherArray.isEmpty()) {
                    description = weatherArray[0].toObject()["description"].toString();
                }
                
                ui->labelWeatherResult->setText(QString("Température: %1°C\nConditions: %2")
                                                .arg(temp, 0, 'f', 1)
                                                .arg(description));
            }
        } else {
            // Fallback display if API is not configured
            ui->labelWeatherResult->setText("Température: 20°C\n(Configuration API requise pour données réelles)");
            QMessageBox::information(this, "Info", "Pour obtenir des données météo réelles, configurez une clé API OpenWeatherMap.");
        }
        reply->deleteLater();
    });
}

void Gestion_Equipement::navigateToCandidat()
{
    QMainWindow *mainWindow = qobject_cast<QMainWindow*>(parent()->parent());
    if (mainWindow) {
        mainWindow->findChild<QStackedWidget*>()->setCurrentIndex(1);
    }
}

void Gestion_Equipement::navigateToPlanning()
{
    QMainWindow *mainWindow = qobject_cast<QMainWindow*>(parent()->parent());
    if (mainWindow) {
        mainWindow->findChild<QStackedWidget*>()->setCurrentIndex(4);
    }
}

void Gestion_Equipement::navigateToEmployee()
{
    QMainWindow *mainWindow = qobject_cast<QMainWindow*>(parent()->parent());
    if (mainWindow) {
        mainWindow->findChild<QStackedWidget*>()->setCurrentIndex(0);
    }
}

void Gestion_Equipement::navigateToVehicule()
{
    QMainWindow *mainWindow = qobject_cast<QMainWindow*>(parent()->parent());
    if (mainWindow) {
        mainWindow->findChild<QStackedWidget*>()->setCurrentIndex(2);
    }
}

void Gestion_Equipement::navigateToExamen()
{
    QMainWindow *mainWindow = qobject_cast<QMainWindow*>(parent()->parent());
    if (mainWindow) {
        mainWindow->findChild<QStackedWidget*>()->setCurrentIndex(3);
    }
}

void Gestion_Equipement::navigateToEquipement()
{
    // Already in equipement view
}

// ==================== HELPER FUNCTIONS ====================

void Gestion_Equipement::clearForm()
{
    ui->id_equipement->clear();
    ui->nom_equipement->clear();
    ui->nom_equipement_2->clear();
    ui->comboBox_equipement->setCurrentIndex(0);
    ui->comboBox->setCurrentIndex(0);
    ui->spinBox_equipement->setValue(0);
    ui->spinBox_equipement1->setValue(0);
    ui->dateEdit->setDate(QDate::currentDate());
}

bool Gestion_Equipement::validateInput()
{
    if (ui->nom_equipement->toPlainText().trimmed().isEmpty()) {
        QMessageBox::warning(this, "Validation", "Le nom de l'équipement est requis.");
        return false;
    }
    
    if (ui->nom_equipement_2->toPlainText().trimmed().isEmpty()) {
        QMessageBox::warning(this, "Validation", "Le fournisseur est requis.");
        return false;
    }
    
    if (ui->spinBox_equipement->value() <= 0) {
        QMessageBox::warning(this, "Validation", "La quantité totale doit être supérieure à 0.");
        return false;
    }
    
    if (ui->spinBox_equipement1->value() > ui->spinBox_equipement->value()) {
        QMessageBox::warning(this, "Validation", "La quantité disponible ne peut pas dépasser la quantité totale.");
        return false;
    }
    
    return true;
}

int Gestion_Equipement::generateNextId()
{
    // Find the smallest available ID
    QSqlQuery query("SELECT ID_EQUIPEMENT FROM EQUIPEMENT ORDER BY ID_EQUIPEMENT ASC");
    
    int expectedId = 1;
    while (query.next()) {
        int currentId = query.value(0).toInt();
        if (currentId != expectedId) {
            // Found a gap, return the missing ID
            return expectedId;
        }
        expectedId++;
    }
    
    // No gaps found, return the next sequential ID
    return expectedId;
}

// ==================== TABLE INTERACTION ====================

void Gestion_Equipement::on_tab_2_clicked(const QModelIndex &index)
{
    int row = index.row();
    
    ui->id_equipement->setText(ui->tab_2->item(row, 0)->text());
    ui->nom_equipement->setText(ui->tab_2->item(row, 1)->text());
    
    QString categorie = ui->tab_2->item(row, 2)->text();
    ui->comboBox_equipement->setCurrentText(categorie);
    
    ui->spinBox_equipement->setValue(ui->tab_2->item(row, 3)->text().toInt());
    ui->spinBox_equipement1->setValue(ui->tab_2->item(row, 4)->text().toInt());
    
    QString etat = ui->tab_2->item(row, 5)->text();
    ui->comboBox->setCurrentText(etat);
    
    ui->nom_equipement_2->setText(ui->tab_2->item(row, 6)->text());
    
    QString dateStr = ui->tab_2->item(row, 7)->text();
    QDate date = QDate::fromString(dateStr, "yyyy-MM-dd");
    ui->dateEdit->setDate(date);
}

// ==================== SEARCH AND FILTER ====================

void Gestion_Equipement::on_recherche_2_textChanged()
{
    QString searchText = ui->recherche_2->toPlainText().trimmed();
    
    if (searchText.isEmpty()) {
        loadTableData();
        return;
    }
    
    QSqlQuery query;
    query.prepare("SELECT ID_EQUIPEMENT, NOM, CATEGORIE, QUANTITE_TOTALE, QUANTITE_DISPONIBLE, ETAT, FOURNISSEUR, DATE_ACQUISITION "
                  "FROM EQUIPEMENT WHERE NOM LIKE :search OR FOURNISSEUR LIKE :search OR CATEGORIE LIKE :search");
    query.bindValue(":search", "%" + searchText + "%");
    
    ui->tab_2->setRowCount(0);
    
    if (query.exec()) {
        int row = 0;
        while (query.next()) {
            ui->tab_2->insertRow(row);
            
            for (int col = 0; col < 8; col++) {
                QTableWidgetItem *item = new QTableWidgetItem(query.value(col).toString());
                if (col == 0) {
                    item->setFlags(item->flags() & ~Qt::ItemIsEditable);
                }
                ui->tab_2->setItem(row, col, item);
            }
            row++;
        }
    }
}

void Gestion_Equipement::on_tri_2_currentIndexChanged(int index)
{
    QString orderBy;
    
    switch(index) {
        case 0: // Default
            loadTableData();
            return;
        case 1: // Name A-Z
            orderBy = "NOM ASC";
            break;
        case 2: // Name Z-A
            orderBy = "NOM DESC";
            break;
        case 3: // Qté Dispo croissant
            orderBy = "QUANTITE_DISPONIBLE ASC";
            break;
        case 4: // Qté Dispo décroissant
            orderBy = "QUANTITE_DISPONIBLE DESC";
            break;
        default:
            loadTableData();
            return;
    }
    
    QSqlQuery query;
    query.prepare(QString("SELECT ID_EQUIPEMENT, NOM, CATEGORIE, QUANTITE_TOTALE, QUANTITE_DISPONIBLE, ETAT, FOURNISSEUR, DATE_ACQUISITION "
                          "FROM EQUIPEMENT ORDER BY %1").arg(orderBy));
    
    ui->tab_2->setRowCount(0);
    
    if (query.exec()) {
        int row = 0;
        while (query.next()) {
            ui->tab_2->insertRow(row);
            
            for (int col = 0; col < 8; col++) {
                QTableWidgetItem *item = new QTableWidgetItem(query.value(col).toString());
                if (col == 0) {
                    item->setFlags(item->flags() & ~Qt::ItemIsEditable);
                }
                ui->tab_2->setItem(row, col, item);
            }
            row++;
        }
    }
}

// ==================== EXPORT FUNCTION ====================

void Gestion_Equipement::on_pushButton_17_clicked()
{
    // Export to CSV
    QString fileName = QFileDialog::getSaveFileName(this, "Exporter en CSV", "", "CSV Files (*.csv)");
    
    if (fileName.isEmpty()) {
        return;
    }
    
    QFile file(fileName);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QMessageBox::critical(this, "Erreur", "Impossible d'ouvrir le fichier pour l'écriture.");
        return;
    }
    
    QTextStream out(&file);
    
    // Write headers
    out << "ID,Nom,Catégorie,Quantité Totale,Quantité Disponible,État,Fournisseur,Date Acquisition\n";
    
    // Write data
    for (int row = 0; row < ui->tab_2->rowCount(); ++row) {
        for (int col = 0; col < ui->tab_2->columnCount(); ++col) {
            QTableWidgetItem *item = ui->tab_2->item(row, col);
            if (item) {
                out << "\"" << item->text() << "\"";
            }
            if (col < ui->tab_2->columnCount() - 1) {
                out << ",";
            }
        }
        out << "\n";
    }
    
    file.close();
    QMessageBox::information(this, "Succès", "Données exportées avec succès!");
}
